# Generated by Django 5.2.4 on 2025-08-07 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["-created_at"], "verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__lte", 120)), name="duration_max_120_seconds"
            ),
        ),
        migrations.AddConstraint(
            model_name="habit",
            constraint=models.CheckConstraint(
                condition=models.Q(("frequency__gte", 1), ("frequency__lte", 7)), name="frequency_between_1_and_7"
            ),
        ),
    ]
